name: 'Python Lint'
on: [push, pull_request]
jobs:
  python_lint:
    runs-on: ubuntu-latest
    name: 'Python Lint'
    steps:
    - uses: actions/checkout@v2
    - name: Python Linter
      uses: baliame/python-linter@master
      with:
        source: "src"
        mypy-options: "--ignore-missing-imports --show-error-codes"
        isort-options: "--profile black"
